#schema: https://taskfile.dev/schema.json
version: '3.17'

tasks:
  lint:
    desc: Run lint
    cmds:
      - golangci-lint run

  test:
    desc: Run tests
    cmds:
      - go test ./... -v -tags=test
      - go test ./... -v -tags=test run=NONE -bench=. -benchmem