name: CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: Lint source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.4.0
          only-new-issues: true

  test:
    name: Test source code
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [ 1.25.x, 1.26.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}

      - name: Setup go-task
        uses: rnorton5432/setup-task@v1
        with:
          task-version: '3.44.0'

      - name: Test
        run: task test

  commitlint:
    name: Lint commit message
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Install commitlint
        run: npm install -D @commitlint/cli @commitlint/config-conventional

      - name: Print versions
        run: |
          git --version
          node --version
          npm --version
          npx commitlint --version

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: npx commitlint --last --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose


  release:
    name: Ensure release can be processed after merge (dry-run)
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_REF: ${{ github.event.pull_request.head.ref }}
        run: npx semantic-release --branches "$BRANCH_REF" --dry-run