name: Commit lint

on:
  pull_request:
    branches:
      - main

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Conventional Commitlint
        uses: opensource-nepal/commitlint@v1.2.0
        with:
          verbose: true