name: golangci-lint

on:
  pull_request:
    branches:
      - main
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.3.4
          only-new-issues: true